services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./event_service:/event_service
    environment:
      DB_HOST: database
      DB_NAME: event_service
      DB_USER: db_user
      DB_PASSWORD: db_password

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:15.2-alpine3.17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=event_service
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password